---
authors:
  - Zach Peterson (zjpeterson)
dependencies:
  "amazon.aws": ">=8.2.0"
  "servicenow.itsm": ">=2.14.0"
license_file: LICENSE
name: labcommon
description: Common lab needs for different environments
namespace: zjpeterson
readme: README.md
repository: https://github.com/zjpeterson/ansible-labcommon
issues: https://github.com/zjpeterson/ansible-labcommon/issues
tags:
  - lab
  - cloud
  - aws
  - azure
  - servicenow
version: 0.4.0
build_ignore:
  - ".ansible"
  - "*.log"
  - "test*"
  - "*.tar.gz"
  - ".git"
  - ".vscode"
