---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ aws_vpc_name }}"
    cidr_block: "{{ aws_vpc_block }}"
    region: "{{ aws_vpc_region }}"
  register: _vpc

- name: Create subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ _vpc.vpc.id }}"
    az: "{{ aws_vpc_region }}a"
    cidr: "{{ aws_vpc_subnet_block }}"
    region: "{{ aws_vpc_region }}"
  register: _subnet

- name: Create internet gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ _vpc.vpc.id }}"
    region: "{{ aws_vpc_region }}"
  register: _igw

- name: Create route table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ _vpc.vpc.id }}"
    subnets: "{{ _subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ _igw.gateway_id }}"
    region: "{{ aws_vpc_region }}"
    tags: # not using this otherwise but makes the task idempotent
      Created-By: ansible

- name: Save IDs for use with EC2 role
  ansible.builtin.set_fact:
    aws_ec2_region: "{{ aws_vpc_region }}"
    aws_ec2_vpc: "{{ _vpc.vpc.id }}"
    aws_ec2_subnet: "{{ _subnet.subnet.id }}"
